import {execSync, spawnSync} from 'node:child_process'
import {copyFileSync, existsSync, mkdtempSync, readFileSync, rmSync} from 'node:fs'
import {homedir, tmpdir} from 'node:os'
import {join} from 'node:path'

import {describe, expect, test} from 'vitest'

import {runTypegenGenerate} from '../../../actions/typegenGenerate.js'

function hasGoToolchain(): boolean {
  try {
    execSync('go version', {stdio: 'ignore'})
    return true
  } catch {
    return false
  }
}

const penguinSchemaPath = join(homedir(), 'programming/sanity/penguin/schema.json')
const penguinGoMod = join(homedir(), 'programming/sanity/penguin/go.mod')

const shouldRun =
  process.env.POLYGLOT_TYPEGEN_PENGUIN === '1' &&
  hasGoToolchain() &&
  existsSync(penguinSchemaPath) &&
  existsSync(penguinGoMod)

const maybeTest = shouldRun ? test : test.skip

describe('Phase 4 checkpoint: penguin schema end-to-end via orchestrator', () => {
  maybeTest(
    'runTypegenGenerate writes a Go file that go build accepts in penguin module',
    async () => {
      const tmp = mkdtempSync(join(tmpdir(), 'sanity-go-e2e-'))
      try {
        const schemaCopy = join(tmp, 'schema.json')
        copyFileSync(penguinSchemaPath, schemaCopy)
        const outputPath = 'pkg/sanitytypes/sanity.gen.go'

        const result = await runTypegenGenerate({
          config: {
            go: {
              generates: `./${outputPath}`,
              packageName: 'sanitytypes',
              schema: './schema.json',
            },
          },
          workDir: tmp,
        })

        expect(result.languages.go).toBeDefined()
        expect(result.languages.go?.status).toBe('success')
        expect(result.languages.go?.stats?.documents).toBeGreaterThan(0)

        const generated = readFileSync(join(tmp, outputPath), 'utf8')
        expect(generated).toContain('// Code generated by Sanity TypeGen. DO NOT EDIT.')
        expect(generated).toContain('package sanitytypes')

        // Drop a penguin-shaped go.mod into the tmp dir so `go build` resolves Go 1.24.
        copyFileSync(penguinGoMod, join(tmp, 'go.mod'))

        const build = spawnSync('go', ['build', './pkg/sanitytypes/...'], {
          cwd: tmp,
          encoding: 'utf8',
        })
        if (build.status !== 0) {
          throw new Error(
            `go build failed in penguin e2e (exit ${build.status}):\nstdout: ${build.stdout}\nstderr: ${build.stderr}`,
          )
        }
        expect(build.status).toBe(0)
      } finally {
        rmSync(tmp, {force: true, recursive: true})
      }
    },
    60_000,
  )
})
