import {mkdtemp, readFile, rm} from 'node:fs/promises'
import {tmpdir} from 'node:os'
import {join} from 'node:path'

import {afterAll, beforeAll, describe, expect, it} from 'vitest'

import {typescriptGenerator} from '../index.js'

/**
 * SC-001 guard for User Story 1. The TypeScript generator was relocated from
 * `src/typescript/` to `src/polyglot/typescript/` and wrapped behind the
 * `LanguageGenerator` interface; the contract is that nothing about the emitted
 * `code` changes for the same input. The regression baseline captured at task T004
 * lives next to this test as `generate.test.ts.snap.pre-polyglot`. We assert the
 * baseline is intact (it must never drift in phase 1) and snapshot the generator's
 * output against the shared kitchen-sink fixture so any future change to the
 * relocated generator surfaces immediately.
 */

const SNAPSHOTS_DIR = join(
  import.meta.dirname,
  '..',
  '..',
  '..',
  'commands',
  'typegen',
  '__tests__',
  '__snapshots__',
)
const KITCHEN_SINK = join(
  import.meta.dirname,
  '..',
  '..',
  '__fixtures__',
  'kitchen-sink-schema.json',
)

describe('typescript generator regression (US1 / SC-001)', () => {
  let workDir: string

  beforeAll(async () => {
    workDir = await mkdtemp(join(tmpdir(), 'polyglot-ts-regression-'))
  })

  afterAll(async () => {
    if (workDir) await rm(workDir, {force: true, recursive: true})
  })

  it('the pre-polyglot snapshot baseline is unchanged', async () => {
    const baseline = await readFile(
      join(SNAPSHOTS_DIR, 'generate.test.ts.snap.pre-polyglot'),
      'utf8',
    )
    expect(baseline.length).toBeGreaterThan(0)
    expect(baseline).toContain(
      `exports[\`#typegen:generate > should generate types from queries 1\`]`,
    )
    expect(baseline).toContain('This file has been generated by Sanity TypeGen.')
    expect(baseline).toMatchSnapshot('pre-polyglot-baseline')
  })

  it('relocated typescriptGenerator emits stable output for the kitchen-sink schema', async () => {
    const config = typescriptGenerator.parseConfig({
      formatGeneratedCode: false,
      generates: join(workDir, 'kitchen-sink.types.ts'),
      path: [join(workDir, 'no-queries-here', '**', '*.ts')],
      schema: KITCHEN_SINK,
    })

    const {code, stats} = await typescriptGenerator.generate({
      config,
      schema: undefined as never,
      workDir,
    })

    expect(code).toContain('This file has been generated by Sanity TypeGen.')
    expect(stats.documents).toBeGreaterThan(0)
    expect(code).toMatchSnapshot('kitchen-sink-output')
  })
})
