import {readFile} from 'node:fs/promises'
import {fileURLToPath} from 'node:url'

import {type SchemaType} from 'groq-js'
import {describe, expect, test} from 'vitest'

import {swiftGenerator} from '../index.js'

const fixtureUrl = new URL('../../__fixtures__/kitchen-sink-schema.json', import.meta.url)

async function loadKitchenSinkSchema(): Promise<SchemaType> {
  const content = await readFile(fileURLToPath(fixtureUrl), 'utf8')
  return JSON.parse(content) as SchemaType
}

describe('swiftGenerator (kitchen sink)', () => {
  test('emits a Codable+Sendable struct per document/object with verbatim _id/_type properties', async () => {
    const schema = await loadKitchenSinkSchema()
    const result = await swiftGenerator.generate({
      config: {
        formatGeneratedCode: true,
        generates: './Sources/App/SanityTypes.swift',
        schema: './schema.json',
      },
      schema,
      workDir: '/tmp',
    })

    expect(result.code).toMatchSnapshot()
    expect(result.stats.documents).toBeGreaterThanOrEqual(3)
    expect(result.stats.objects).toBeGreaterThanOrEqual(1)
  })

  test('preserves leading underscores on Codable properties (so synthesis works without CodingKeys)', async () => {
    const schema = await loadKitchenSinkSchema()
    const {code} = await swiftGenerator.generate({
      config: {
        generates: './Sources/App/SanityTypes.swift',
        schema: './schema.json',
      },
      schema,
      workDir: '/tmp',
    })
    expect(code).toMatch(/public let _id: String\b/)
    expect(code).toMatch(/public let _type: String\b/)
    expect(code).toMatch(/public let _createdAt: String\??/)
    expect(code).toMatch(/public let _updatedAt: String\??/)
    expect(code).toMatch(/public let _rev: String\??/)
  })

  test('emits the import Foundation + import Sanity prelude exactly once', async () => {
    const schema = await loadKitchenSinkSchema()
    const {code} = await swiftGenerator.generate({
      config: {
        generates: './Sources/App/SanityTypes.swift',
        schema: './schema.json',
      },
      schema,
      workDir: '/tmp',
    })
    expect(code).toMatch(/^\/\/ Code generated by Sanity TypeGen\. DO NOT EDIT\./)
    const sanityImports = code.match(/^import Sanity$/gm) ?? []
    const foundationImports = code.match(/^import Foundation$/gm) ?? []
    expect(sanityImports).toHaveLength(1)
    expect(foundationImports).toHaveLength(1)
  })

  test('emits Identifiable conformance on documents only', async () => {
    const schema = await loadKitchenSinkSchema()
    const {code} = await swiftGenerator.generate({
      config: {
        generates: './Sources/App/SanityTypes.swift',
        schema: './schema.json',
      },
      schema,
      workDir: '/tmp',
    })
    // Documents include `Identifiable`; named objects do not.
    expect(code).toMatch(/public struct Post: Codable, Sendable, Identifiable \{/)
    expect(code).toMatch(/public struct Link: Codable, Sendable \{/)
    expect(code).toMatch(/public var id: String \{ _id \}/)
  })

  test('emits a discriminated-union enum for union-of-types arrays', async () => {
    const schema = await loadKitchenSinkSchema()
    const {code} = await swiftGenerator.generate({
      config: {
        generates: './Sources/App/SanityTypes.swift',
        schema: './schema.json',
      },
      schema,
      workDir: '/tmp',
    })
    expect(code).toMatch(/public enum PostBody: Codable, Sendable \{/)
    expect(code).toMatch(/private enum DiscriminatorKeys: String, CodingKey \{ case _type \}/)
    expect(code).toMatch(/public init\(from decoder: Decoder\) throws \{/)
    expect(code).toMatch(/public func encode\(to encoder: Encoder\) throws \{/)
  })
})

describe('swiftGenerator config validation', () => {
  test('rejects missing schema', () => {
    expect(() => swiftGenerator.parseConfig({generates: './Out.swift'})).toThrow(/schema/)
  })

  test('rejects missing generates', () => {
    expect(() => swiftGenerator.parseConfig({schema: './schema.json'})).toThrow(/generates/)
  })

  test("rejects generates without '.swift' extension", () => {
    expect(() =>
      swiftGenerator.parseConfig({generates: './Out.txt', schema: './schema.json'}),
    ).toThrow(/\.swift/)
  })
})
