import {basename, dirname} from 'node:path'

import {type BaseLanguageConfig, type GenerationOutput, type LanguageGenerator} from '../index.js'
import {emitGoBody} from './emit.js'

/** @public */
export interface GoLanguageConfig extends BaseLanguageConfig {
  packageName?: string
}

const PACKAGE_NAME_PATTERN = /^[a-z][a-z0-9_]*$/

function deriveDefaultPackageName(generates: string): string {
  const dir = basename(dirname(generates))
  const sanitized = dir.replaceAll(/[^a-z0-9_]/gi, '').toLowerCase()
  if (sanitized && PACKAGE_NAME_PATTERN.test(sanitized)) return sanitized
  return 'sanitytypes'
}

function parseGoConfig(raw: unknown): GoLanguageConfig {
  if (raw === null || raw === undefined) raw = {}
  if (typeof raw !== 'object' || Array.isArray(raw)) {
    throw new TypeError('go config: must be an object')
  }
  const block = raw as Record<string, unknown>
  if (typeof block.schema !== 'string' || block.schema.length === 0) {
    throw new Error('go config: `schema` is required and must be a non-empty string')
  }
  if (typeof block.generates !== 'string' || block.generates.length === 0) {
    throw new Error('go config: `generates` is required and must be a non-empty string')
  }
  if (!block.generates.endsWith('.go')) {
    throw new Error(`go config: \`generates\` must end with '.go' (got ${block.generates})`)
  }
  const packageName =
    block.packageName === undefined
      ? deriveDefaultPackageName(block.generates)
      : String(block.packageName)
  if (!PACKAGE_NAME_PATTERN.test(packageName)) {
    throw new Error(
      `go config: \`packageName\` must match /^[a-z][a-z0-9_]*$/ (got '${packageName}')`,
    )
  }
  // The TS-only formatters in `resolveFormatter` (prettier/oxfmt) would corrupt `.go`
  // output if applied. The emitter already produces gofmt-aligned code, so default
  // formatting OFF and only honor an explicit user opt-in.
  const formatGeneratedCode =
    block.formatGeneratedCode === undefined
      ? false
      : (block.formatGeneratedCode as 'oxfmt' | 'prettier' | boolean)
  return {
    formatGeneratedCode,
    generates: block.generates,
    packageName,
    schema: block.schema,
  }
}

function renderFile(opts: {
  body: string
  imports: string[]
  packageName: string
  schemaPath: string
}): string {
  const {body, imports, packageName, schemaPath} = opts
  const lines: string[] = [
    '// Code generated by Sanity TypeGen. DO NOT EDIT.',
    `// Source schema: ${schemaPath}`,
    '',
    `package ${packageName}`,
  ]
  if (imports.length > 0) {
    lines.push('')
    if (imports.length === 1) {
      lines.push(`import "${imports[0]}"`)
    } else {
      lines.push('import (')
      for (const imp of imports) {
        lines.push(`\t"${imp}"`)
      }
      lines.push(')')
    }
  }
  if (body.length > 0) {
    lines.push('', body)
  }
  // Ensure trailing newline.
  return `${lines.join('\n')}\n`
}

/** @public */
export const goGenerator: LanguageGenerator<GoLanguageConfig> = {
  fileExtension: '.go',
  generate({config, schema}): Promise<GenerationOutput> {
    const {body, imports, stats} = emitGoBody(schema)
    const code = renderFile({
      body,
      imports,
      packageName: config.packageName ?? deriveDefaultPackageName(config.generates),
      schemaPath: config.schema,
    })
    return Promise.resolve({code, stats})
  },
  id: 'go',
  parseConfig: parseGoConfig,
}
