import {readFile, writeFile} from 'node:fs/promises'
import {join} from 'node:path'

import {testCommand, testFixture} from '@sanity/cli-test'
import {describe, expect, test} from 'vitest'

import {TypegenGenerateCommand} from '../generate.js'

describe('#typegen:generate (US1 acceptance scenarios)', () => {
  test('emits the deprecation warning exactly once when typegen uses the flat legacy shape', async () => {
    const cwd = await testFixture('dev')
    process.chdir(cwd)

    await writeFile(
      join(cwd, 'sanity.cli.ts'),
      `import {defineCliConfig} from 'sanity/cli'

      export default defineCliConfig({
        typegen: {
          schema: './schema.json',
          generates: './sanity.types.ts',
        }
      })
    `.trim(),
    )

    const {error, stderr, stdout} = await testCommand(TypegenGenerateCommand, [])

    expect(error).toBeUndefined()

    const haystack = `${stderr}\n${stdout}`
    const expected =
      "warn  The flat 'typegen' config is deprecated. Move your fields under 'typegen.typescript'."

    const matches = haystack.split(expected).length - 1
    expect(matches).toBe(1)
  })

  test('typegen.typescript alone runs only the TypeScript row and exits 0', async () => {
    const cwd = await testFixture('dev')
    process.chdir(cwd)

    await writeFile(
      join(cwd, 'sanity.cli.ts'),
      `import {defineCliConfig} from 'sanity/cli'

      export default defineCliConfig({
        typegen: {
          typescript: {
            schema: './schema.json',
            generates: './sanity.types.ts',
          },
        }
      })
    `.trim(),
    )

    const {error, stderr, stdout} = await testCommand(TypegenGenerateCommand, [])

    expect(error).toBeUndefined()

    const haystack = `${stderr}\n${stdout}`
    expect(haystack).toContain('typescript →')
    expect(haystack).not.toContain('go →')
    expect(haystack).not.toContain('php →')
    expect(haystack).not.toContain('swift →')
    expect(haystack).not.toContain('deprecated')

    const written = await readFile(join(cwd, 'sanity.types.ts'), 'utf8')
    expect(written).toContain('This file has been generated by Sanity TypeGen.')
  })

  test('mixed legacy + per-language form fails before any I/O', async () => {
    const cwd = await testFixture('dev')
    process.chdir(cwd)

    await writeFile(
      join(cwd, 'sanity.cli.ts'),
      `import {defineCliConfig} from 'sanity/cli'

      export default defineCliConfig({
        typegen: {
          schema: './schema.json',
          generates: './sanity.types.ts',
          typescript: {
            schema: './schema.json',
            generates: './sanity.types.ts',
          },
        }
      })
    `.trim(),
    )

    const {error} = await testCommand(TypegenGenerateCommand, [])

    expect(error).toBeDefined()
    expect(error?.message).toContain(
      'typegen has both legacy fields and per-language blocks; use one form',
    )
    expect(error?.oclif?.exit).toBe(1)
  })
})
