import {existsSync} from 'node:fs'
import {copyFile, readFile, writeFile} from 'node:fs/promises'
import {join} from 'node:path'
import {fileURLToPath} from 'node:url'

import {testCommand, testFixture} from '@sanity/cli-test'
import {describe, expect, test} from 'vitest'

import {TypegenGenerateCommand} from '../generate.js'

const kitchenSinkUrl = new URL(
  '../../../polyglot/__fixtures__/kitchen-sink-schema.json',
  import.meta.url,
)

describe('#typegen:generate (US5 — all four languages)', () => {
  test('emits all four outputs in one CLI invocation', async () => {
    const cwd = await testFixture('dev')
    process.chdir(cwd)

    await copyFile(fileURLToPath(kitchenSinkUrl), join(cwd, 'schema.json'))

    await writeFile(
      join(cwd, 'sanity.cli.ts'),
      `import {defineCliConfig} from 'sanity/cli'

      export default defineCliConfig({
        typegen: {
          typescript: {
            schema: './schema.json',
            generates: './sanity.types.ts',
            formatGeneratedCode: false,
          },
          go: {
            schema: './schema.json',
            generates: './sanity.gen.go',
            packageName: 'sanitytypes',
            formatGeneratedCode: false,
          },
          php: {
            schema: './schema.json',
            generates: './Sanity.php',
            namespace: 'Sanity\\\\Generated',
            formatGeneratedCode: false,
          },
          swift: {
            schema: './schema.json',
            generates: './Sanity.swift',
            formatGeneratedCode: false,
          },
        }
      })
    `.trim(),
    )

    const {error, stderr, stdout} = await testCommand(TypegenGenerateCommand, [])

    expect(error).toBeUndefined()

    const haystack = `${stderr}\n${stdout}`
    expect(haystack).toContain('typescript →')
    expect(haystack).toContain('go →')
    expect(haystack).toContain('php →')
    expect(haystack).toContain('swift →')

    const noteMatches = haystack.split("Swift output uses 'import Sanity'.").length - 1
    expect(noteMatches).toBe(1)

    expect(existsSync(join(cwd, 'sanity.types.ts'))).toBe(true)
    expect(existsSync(join(cwd, 'sanity.gen.go'))).toBe(true)
    expect(existsSync(join(cwd, 'Sanity.php'))).toBe(true)
    expect(existsSync(join(cwd, 'Sanity.swift'))).toBe(true)

    const goOut = await readFile(join(cwd, 'sanity.gen.go'), 'utf8')
    expect(goOut).toMatch(/^package sanitytypes/m)
    const phpOut = await readFile(join(cwd, 'Sanity.php'), 'utf8')
    expect(phpOut).toContain('namespace Sanity\\Generated;')
    const swiftOut = await readFile(join(cwd, 'Sanity.swift'), 'utf8')
    expect(swiftOut).toContain('import Sanity')
    const tsOut = await readFile(join(cwd, 'sanity.types.ts'), 'utf8')
    expect(tsOut).toContain('This file has been generated by Sanity TypeGen.')
  })
})
