import {type BaseLanguageConfig, type GenerationOutput, type LanguageGenerator} from '../index.js'
import {emitSwiftCode} from './emit.js'

/** @public */
export type SwiftLanguageConfig = BaseLanguageConfig

const BANNER = `// Code generated by Sanity TypeGen. DO NOT EDIT.\n`
const IMPORTS = `import Foundation\nimport Sanity\n\n`

function parseSwiftConfig(raw: unknown): SwiftLanguageConfig {
  if (raw === null || raw === undefined) raw = {}
  if (typeof raw !== 'object' || Array.isArray(raw)) {
    throw new TypeError('swift config: must be an object')
  }
  const block = raw as Record<string, unknown>
  if (typeof block.schema !== 'string' || block.schema.length === 0) {
    throw new TypeError('swift config: `schema` is required and must be a non-empty string')
  }
  if (typeof block.generates !== 'string' || block.generates.length === 0) {
    throw new TypeError('swift config: `generates` is required and must be a non-empty string')
  }
  if (!block.generates.endsWith('.swift')) {
    throw new TypeError("swift config: `generates` must end in '.swift'")
  }
  const formatGeneratedCode =
    block.formatGeneratedCode === undefined
      ? true
      : (block.formatGeneratedCode as 'oxfmt' | 'prettier' | boolean)
  return {
    formatGeneratedCode,
    generates: block.generates,
    schema: block.schema,
  }
}

/** @public */
export const swiftGenerator: LanguageGenerator<SwiftLanguageConfig> = {
  fileExtension: '.swift',
  async generate({config, schema}): Promise<GenerationOutput> {
    const sourceComment = `// Source schema: ${config.schema}\n\n`
    const {code, stats} = emitSwiftCode(schema)
    const full = `${BANNER}${sourceComment}${IMPORTS}${code}`
    const normalized = full.endsWith('\n') ? full : `${full}\n`
    return {code: normalized, stats}
  },
  id: 'swift',
  parseConfig: parseSwiftConfig,
}
