import {type BaseLanguageConfig, type GenerationOutput, type LanguageGenerator} from '../index.js'
import {emit} from './emit.js'
import {SANITY_PHP_RESERVED_CLASSES} from './sanity-php-reserved.js'

/** @public */
export interface PhpLanguageConfig extends BaseLanguageConfig {
  namespace?: string
}

const DEFAULT_NAMESPACE = String.raw`Sanity\Generated`
const NAMESPACE_PATTERN = /^[A-Z][A-Za-z0-9_]*(\\[A-Z][A-Za-z0-9_]*)*$/

function parsePhpConfig(raw: unknown): PhpLanguageConfig {
  if (raw === null || raw === undefined) raw = {}
  if (typeof raw !== 'object' || Array.isArray(raw)) {
    throw new TypeError('php config: must be an object')
  }
  const block = raw as Record<string, unknown>
  if (typeof block.schema !== 'string' || block.schema.length === 0) {
    throw new TypeError('php config: `schema` is required and must be a string path')
  }
  if (typeof block.generates !== 'string' || block.generates.length === 0) {
    throw new TypeError('php config: `generates` is required and must be a string path')
  }
  if (!block.generates.endsWith('.php')) {
    throw new TypeError(`php config: \`generates\` must end with .php (got ${block.generates})`)
  }

  let namespace: string = DEFAULT_NAMESPACE
  if (block.namespace !== undefined) {
    if (typeof block.namespace !== 'string') {
      throw new TypeError('php config: `namespace` must be a string')
    }
    if (!NAMESPACE_PATTERN.test(block.namespace)) {
      throw new TypeError(
        `php config: \`namespace\` must match ${NAMESPACE_PATTERN} (got ${block.namespace})`,
      )
    }
    namespace = block.namespace
  }

  const formatGeneratedCode =
    block.formatGeneratedCode === undefined
      ? true
      : (block.formatGeneratedCode as 'oxfmt' | 'prettier' | boolean)

  return {
    formatGeneratedCode,
    generates: block.generates,
    namespace,
    schema: block.schema,
  }
}

/** @public */
export const phpGenerator: LanguageGenerator<PhpLanguageConfig> = {
  fileExtension: '.php',
  async generate({config, schema}): Promise<GenerationOutput> {
    const namespace = config.namespace ?? DEFAULT_NAMESPACE
    const {body, documentCount, objectCount, skipped} = emit({
      namespace,
      reservedClasses: SANITY_PHP_RESERVED_CLASSES,
      schema,
    })

    const header =
      `<?php\n` +
      `// Code generated by Sanity TypeGen. DO NOT EDIT.\n` +
      `// Source schema: ${config.schema}\n` +
      `\n` +
      `declare(strict_types=1);\n` +
      `\n` +
      `namespace ${namespace};\n`

    const code = `${header}\n${body}\n`

    return {
      code,
      stats: {
        documents: documentCount,
        objects: objectCount,
        skipped,
      },
    }
  },
  id: 'php',
  parseConfig: parsePhpConfig,
}
